# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    container_name: acumos-elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - acumos-esdata:/usr/share/elasticsearch/data
    ports:
    #Node client default listens at 9200, metricbeat and logstash index data into Elasticsearch using this port.
     - "${ACUMOS_ELK_ELASTICSEARCH_PORT}:9200"
    #Transport client default is 9300 this port is used for nodes communication. If this port is not open, your nodes will not be able to form a cluster.
     - "${ACUMOS_ELK_NODE_PORT}:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx${ACUMOS_ELK_ES_JAVA_HEAP_MAX_SIZE} -Xms${ACUMOS_ELK_ES_JAVA_HEAP_MIN_SIZE}"
    networks:
      - elk

  logstash:
    build: logstash/
    container_name: acumos-logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
    #Logstash default listens at 5000, Filebeat agentship log to this port.
      - "${ACUMOS_ELK_LOGSTASH_PORT}:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx${ACUMOS_ELK_LS_JAVA_HEAP_MAX_SIZE} -Xms${ACUMOS_ELK_LS_JAVA_HEAP_MIN_SIZE}"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    container_name: acumos-kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
    #Kiban is accessed on the web browser. Used for visualization of logs.
      - "${ACUMOS_ELK_KIBANA_PORT}:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch


networks:
  elk:
    driver: bridge

volumes:
    acumos-esdata:
        external: true
